name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Calendar Test
      id: calendar-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Calendar Test
        setup-command: ''
        command: gradle test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CALENDAR-TEST_RESULTS: "${{steps.calendar-test.outputs.result}}"
      with:
        runners: calendar-test
